create table acronym
(
    id      integer      not null generated by default as identity,
    acronym varchar(255) not null,
    primary key (id),
    unique (acronym)
);

create table explanation
(
    id          integer        not null generated by default as identity,
    acronym_id  integer        not null,
    explanation varchar(32600) not null,
    author_id   varchar(255)   null,
    primary key (id),
    unique (acronym_id, explanation)
);

alter table explanation
    add constraint fk_explanation_to_acronym
        foreign key (acronym_id)
            references acronym (id);
