create table acronym
(
    id      integer generated by default as identity,
    acronym varchar(255),
    primary key (id),
    unique (acronym)
);

create table explanation
(
    id          integer generated by default as identity,
    acronym_id  integer,
    explanation varchar(32600),
    author_id   varchar(255),
    primary key (id),
    unique (acronym_id, explanation)
);

alter table explanation
    add constraint fk_explanation_to_acronym
        foreign key (acronym_id)
            references acronym (id);
